"""Initial database schema

Revision ID: 49ba81c89f64
Revises: 
Create Date: 2026-08-16 17:49:22.668728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ba81c89f64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_id', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
sa.Column('user_id', sa.String(length=36), nullable=True),    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('registration_id', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_location', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('years_in_operation', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delivery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compliance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('financial_stability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('previous_incidents', sa.Integer(), nullable=True),
    sa.Column('indigenous_claim', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='check_risk_level'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'partially_verified', 'unverified', 'requires_review')", name='check_verification_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_supplier_risk', ['risk_level'], unique=False)
        batch_op.create_index('idx_supplier_status', ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_organization_id'), ['organization_id'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('component_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_location', sa.Text(), nullable=True),
    sa.Column('indigenous_status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('certification', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("category IN ('Semiconductor', 'Microcontroller', 'Sensor', 'PCB', 'Power IC', 'Memory', 'Communication Module', 'Power Electronics', 'Other')", name='check_component_category'),
    sa.CheckConstraint("indigenous_status IN ('indigenous', 'imported', 'unknown')", name='check_indigenous_status'),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='check_component_risk'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'partially_verified', 'unverified', 'requires_review')", name='check_component_verification'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index('idx_component_category', ['category'], unique=False)
        batch_op.create_index('idx_component_indigenous', ['indigenous_status'], unique=False)
        batch_op.create_index('idx_component_supplier', ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("document_type IN ('Company Registration', 'Product Certificate', 'Manufacturing Certificate', 'Quality Certificate', 'Compliance Certificate', 'Origin Documentation', 'Other')", name='check_document_type'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected')", name='check_document_verification'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('assessment_summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='check_assessment_risk_level'),
    sa.CheckConstraint('supplier_id IS NOT NULL OR component_id IS NOT NULL', name='check_assessment_target'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('checked_fields', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('documents_reviewed', sa.JSON(), nullable=True),
sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'partially_verified', 'unverified', 'requires_review')", name='check_record_status'),
    sa.CheckConstraint('supplier_id IS NOT NULL OR component_id IS NOT NULL', name='check_record_target'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('factor_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contribution', sa.String(length=20), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.CheckConstraint("contribution IN ('positive', 'negative', 'neutral')", name='check_contribution'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_factors')
    op.drop_table('verification_records')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_component_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_documents_component_id'))

    op.drop_table('documents')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_supplier_id'))
        batch_op.drop_index('idx_component_supplier')
        batch_op.drop_index('idx_component_indigenous')
        batch_op.drop_index('idx_component_category')

    op.drop_table('components')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_organization_id'))
        batch_op.drop_index('idx_supplier_status')
        batch_op.drop_index('idx_supplier_risk')
        batch_op.drop_index('idx_supplier_org')

    op.drop_table('suppliers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
